photos_dir: ~/Pictures/test-tagging
model: florence2://base # using Florence-2-base
clip_top_k: 5
confidence_threshold: 0.5
output_format: xmp

# Florence-2 specific settings
florence_prompt: "List key nouns in this image, comma separated."
